env:
  global:
  - PYTHONIOENCODING=utf-8                     # fix for UnicodeEncodeError: 'charmap' codec can't encode character '\u251c' in position 1: character maps to <undefined>
install:
- pip install requests
- pip install pyinstaller
- wget -P "./" "https://github.com/SupinePandora43/gmod-manager/releases/download/0.1.0/gmad.exe"

jobs:
  include:
    - stage: test
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
      - choco install --x86 python

branches:
  only:
    - master

script:
- python main.py                                                                            # nothing
- python main.py -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771611119 # addon
- python main.py -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771627899 # collection
- python main.py                                                                            # nothing
- pyinstaller --onefile main.py -n gmod-manager                                             # build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./dist/gmod-manager.exe
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
    branch: master
