env:
  global:
  - PYTHONIOENCODING=utf-8                     # fix for UnicodeEncodeError: 'charmap' codec can't encode character '\u251c' in position 1: character maps to <undefined>
install:
- pip install requests
- pip install pyinstaller
- wget -P "./" "https://github.com/SupinePandora43/gmod-manager/releases/download/0.1.0/gmad.exe"

jobs:
  include:
    - stage: test
      os: windows
      language: shell
      cache:
        directories:
        - /c/Python37
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      before_install:
      - choco install --x86 python
    # - os: linux
    #   language: python
    #   python: "3.6"
    #   env: ARGS=-nogmad

script:
- python main.py $ARGS                                                                            # nothing
- python main.py $ARGS -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771611119 # addon
- python main.py $ARGS -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771627899 # collection
- python main.py $ARGS                                                                            # nothing
- pyinstaller --onefile main.py -n gmod-manager                                                   #build
- ls ./dist
before_deploy:
- export TRAVIS_TAG=$(date +'%Y.%m.%d.%H:%M.%S')
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./dist/gmod-manager.exe
  skip_cleanup: true
  name: $TRAVIS_COMMIT_MESSAGE
  on:
    branch: master
