env:
  global:
  - PYTHONIOENCODING=utf-8   # fix for UnicodeEncodeError: 'charmap' codec can't encode character '\u251c' in position 1: character maps to <undefined>

jobs:
  include:
    - stage: test
      os: windows
      language: shell
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      if: tag IS present
      before_install:
      - choco install --x86 python
    - stage: test
      sudo: required
      os: linux
      language: python
      python: 3.6

branches:
  only:
    - master
    - /v?[0-9]+\.[0-9]+\.[0-9]+(.*)?/

script:
- python main.py -download                                                                  # download gmad
- python main.py -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771611119 # addon
- python main.py -install https://steamcommunity.com/sharedfiles/filedetails/?id=1771627899 # collection
- python main.py                                                                            # nothing

before_deploy:
- pyinstaller --onefile main.py -n gmod-manager                                             # build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: ./dist/*
  skip_cleanup: true
  name: $TRAVIS_TAG
  on:
    tags: true
    branch: master
